"""create initial schema

Revision ID: 4a41d54b1ddd
Revises: 
Create Date: 2026-03-23 20:31:14.411628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a41d54b1ddd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.Enum('classification', 'qa_with_context', 'structured_extraction', 'tool_using_agent', name='task_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.Enum('http', 'python_adapter', name='target_type_enum'), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('endpoint_path', sa.String(length=200), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('headers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('timeout_ms > 0', name='ck_targets_timeout_ms_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dataset_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('case_key', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.Enum('classification', 'qa_with_context', 'structured_extraction', 'tool_using_agent', name='task_type_enum'), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'case_key', name='uq_dataset_case_key')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='run_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_runs_dataset_created_at', 'runs', ['dataset_id', 'created_at'], unique=False)
    op.create_index('ix_runs_status_created_at', 'runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_runs_target_created_at', 'runs', ['target_id', 'created_at'], unique=False)
    op.create_table('run_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('dataset_case_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', 'error', 'invalid_case', name='result_status_enum'), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('expected_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actual_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name='ck_run_results_latency_non_negative'),
    sa.ForeignKeyConstraint(['dataset_case_id'], ['dataset_cases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'dataset_case_id', name='uq_run_result_case')
    )
    op.create_index('ix_run_results_run_created_at', 'run_results', ['run_id', 'created_at'], unique=False)
    op.create_index('ix_run_results_run_status', 'run_results', ['run_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_results_run_status', table_name='run_results')
    op.drop_index('ix_run_results_run_created_at', table_name='run_results')
    op.drop_table('run_results')
    op.drop_index('ix_runs_target_created_at', table_name='runs')
    op.drop_index('ix_runs_status_created_at', table_name='runs')
    op.drop_index('ix_runs_dataset_created_at', table_name='runs')
    op.drop_table('runs')
    op.drop_table('dataset_cases')
    op.drop_table('targets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
